name: cliente
description: "Cliente para Sistema de Chat - Projeto Segurança da Informação"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  web_socket_channel: ^2.4.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  sqflite: ^2.4.2
  path: ^1.9.1
  argon2: ^1.0.1
  cryptography: ^2.7.0
  pointycastle: ^3.7.3
  asn1lib: ^1.1.2
  crypto: ^3.0.3
  dargon2_flutter: ^3.3.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true